import type { NextPage } from 'next';
import Head from 'next/head';
import Drawer from '../components/Drawer';
import Layout from '../components/Layout';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer />
    </Layout>
  );
};

export default Home;
