import type { NextPage } from 'next';
import Head from 'next/head';
import Drawer from '../components/Drawer';
import Layout from '../components/Layout';
import { Container, Flex, Input, InputGroup, InputLeftElement, Select, Text, useColorModeValue, VStack } from '@chakra-ui/react';
import { SearchIcon } from '@chakra-ui/icons';
import Table from '../components/Table';
import { categories } from '../data/categories';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>ForumBase | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container maxW='container.lg' my={10}>
        <VStack spacing={8}>

          {/* Create Post Button + Search Input */}
          <Flex w='full' alignItems={'center'} gap={{ base: 4, sm: 6, lg: 8 }}>

            <Drawer />

            <InputGroup flex={1}>
              <InputLeftElement mt={1}>
                <SearchIcon />
              </InputLeftElement>

              <Input
                id='search'
                name='search'
                placeholder='Search Post'
                size='lg'
                bg={useColorModeValue('white', 'gray.700')}
                _placeholder={{ color: useColorModeValue('gray.900', 'gray.200') }}
              />
            </InputGroup>
          </Flex>

          {/* Mobile - Category Filter Selection (Up to md size)*/}
          <Flex
            w='full'
            display={{ base: 'flex', md: 'none' }}
            alignItems={'center'}
            gap={3}>

            <Text fontWeight={'semibold'}>Category: </Text>
            <Select id='category' name='category' bg={useColorModeValue('white', 'gray.700')}>
              <option value="all">ALL</option>
              {
                categories.map(category =>
                  <option key={category.title} value={category.title}>{category.title}</option>
                )
              }
            </Select>
          </Flex>

          {/* Md and greater -> Category Select + Posts */}
          <Flex
            w='full'
            display={{ base: 'none', md: 'flex' }}
          >
            <Table />
          </Flex>

        </VStack>
      </Container>
    </Layout>
  );
};

export default Home;
